kind: Service
apiVersion: v1
metadata:
  name: hello-helidon
  labels:
    app: hello-helidon
spec:
  type: NodePort
  selector:
    app: hello-helidon
  ports:
  - port: 8080
    targetPort: 8080
    name: http
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: hello-helidon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-helidon
  template:
    metadata:
      labels:
        app: hello-helidon
        version: v1
    spec:
      containers:
      - name: hello-helidon
        image: hello-helidon
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
